services:
  - type: web
    name: image-color-converter
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --config gunicorn_config.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
